dir-overlay: fail if update module is not executed by a superuser
The goal of this module is to preserve ownership and mode attributes of
the files and directories that are being installed. This can only be
accomplished if the module is executed with UID = 0.

Changelog: None

Signed-off-by: Mirza Krak <mirza.krak@northern.tech>

diff --git a/dir-overlay/module/dir-overlay b/dir-overlay/module/dir-overlay
--- a/dir-overlay/module/dir-overlay
+++ b/dir-overlay/module/dir-overlay
@@ -62,11 +62,21 @@ case "$STATE" in
     ;;
 
     ArtifactInstall)
+        if [ $UID -ne 0 ] ; then
+            echo "This update module must be run by a superuser. Aborting..."
+            exit 1
+        fi
+
         dest_dir=$(cat $dest_dir_file)
         mkdir -p $dest_dir $state_dir
 
         if [ -e $manifest_file ]; then
             mkdir -p $backup_dir
+
+            # Copy permissions and ownership from destination directory
+            chmod $(stat -c %a $dest_dir) $backup_dir
+            chown $(stat -c "%U:%G" $dest_dir) $backup_dir
+
             for file in $(cat $manifest_file); do
                 tar -cpf - $dest_dir/$file | (cd $backup_dir/ && tar -xpf -)
             done
@@ -85,10 +95,18 @@ case "$STATE" in
         ;;
 
     ArtifactCommit)
+        if [ $UID -ne 0 ] ; then
+            echo "This update module must be run by a superuser. Aborting..."
+            exit 1
+        fi
         mv $manifest_file_from_deployment $manifest_file
         ;;
 
     ArtifactRollback)
+        if [ $UID -ne 0 ] ; then
+            echo "This update module must be run by a superuser. Aborting..."
+            exit 1
+        fi
         dest_dir=$(cat $dest_dir_file)
 
         test -f $prev_files_tar || exit 0
